@API_HostAddress = http://localhost:5001

GET {{API_HostAddress}}/health
GET {{API_HostAddress}}/api/analysis/status
POST {{API_HostAddress}}/api/analysis/query
POST {{API_HostAddress}}/api/analysis/upload
Accept: application/json

###
